title: WeatherData library for C# developers
description: Library that gives you a Weather data from different REStful web services (in C#)
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
